public  class MathPractice {
    public Decimal practiceOne (Decimal width, Decimal height ) {
     return (2 * (width+height));
    }

    public Decimal practiceTwo (decimal boy, decimal kilo){
        return ( kilo / (boy * boy));
    }
    
    public Decimal practiceThree (decimal num1, decimal num2){
        return ((num1+num2) / 2);
    }

   public String practiceFour (String siparis, Integer tutar){
     public string = parametre;
         if (tutar <= 49) {
            parametre = 'Bonus kazanamadiniz';
         }
         else if (tutar >= 50 && tutar <=199){
            parametre = '100$ tutarındaki alışveriş karşılığı 10 $ tutarında bonus kazandınız';
         }
         else if  tutar >= 200 && tutar <=499 {
            parametre = '300$ tutarındaki alışveriş karşılığı 30 $ tutarında bonus kazandınız';
         }
         else tutar >=500;
         parametre = '750$ tutarındaki alışveriş karşılığı 50 $ tutarında bonus kazandınız.';*/

         if (tutar <= 0) {
             parametre = ' Hatalı bir değer girdiniz.';
         }
         else if (tutar >= 0)  }
}