public class SalesforceDevoleper {
    public void myFirstCode() {

String myFavoriteCity = 'Antalya';
System.debug(myFavoriteCity);

String myFavoriteMovie = 'Yesil Yol';
System.debug(myFavoriteMovie);

String myFavoriteSeason = 'Spring';
System.debug(myFavoriteSeason);

    }
    public void myLife(){
    
String liveCity = 'Amerika';
System.debug(liveCity);

Integer enNum = 22;
System.debug(enNum);

System.debug('Favori numaram ->' +  enNum + 've' + 'Favori sehrim ->' + liveCity );
    } 

}

