EdaPara eda = new EdaPara();
eda.num = 34;
String islem3 = (eda.cevaplama());
system.debug(islem3);


eda.num = 1;
String islem2 = (eda.cevaplama());
System.debug(islem2);




eda.language ='English';
string islem1 = (eda.SelamlamaMetodu());
system.debug(islem1);

eda.language = 'Turkish';
system.debug(eda.SelamlamaMetodu());

eda.language = 'Hispanic';
string islem3=eda.SelamlamaMetodu();
system.debug(islem3);





