System.debug('Eda sen cok mushteshemsin');
String nameParasit = 'Ismi Lazim deyil ';
string gitsinDefolsun = 'bizden uzak Allaha yakin';

System.debug(nameParasit + gitsinDefolsun);


MyCity sehirTry = new MyCity();
sehirTry.cityInformation();

MyCity  yeniVar = new MyCity();
yeniVar.stringMethod();


MyCity dat01 = new MyCity();
dat01.dateMethod();

MyCity cit01 = new MyCity();
cit01.cityInformations();